In [2]:
import h5py
import numpy as np

In [3]:
a = ['fd', 'fds', 'tg']
print a.pop(-1)
print a

tg
['fd', 'fds']


In [4]:
f = h5py.File('/home/niuchuang/PycharmProjects/KLSA-auroral-images/Data/Features/type4_SIFTWords_h1.hdf5', 'r')

In [5]:
c1 = f.get('common_vectors')

In [6]:
for i in c1:
    print i

common_vec_1
common_vec_2


In [37]:
for i in range(4):
    for j in range(i+1, 4):
        print i, j

0 1
0 2
0 3
1 2
1 3
2 3


In [38]:
a = np.random.random((3, 4))
print a

[[ 0.57491879  0.20731449  0.2842348   0.23787068]
 [ 0.90437903  0.45406103  0.23506968  0.77867268]
 [ 0.58593981  0.2553681   0.75180163  0.47273268]]


In [40]:
print np.min(a, axis=1).shape
print np.argmin(a, axis=1).shape

(3,)
(3,)


In [11]:
a = {'d': 1, 'f': 3}
b = {'r': 5, 'w': 2}
c = dict(a.items() + b.items())
print c
c = 

SyntaxError: invalid syntax (<ipython-input-11-a210889f0ecf>, line 5)